apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: i-manmeetdevgun-develop
  name: i-manmeetdevgun-develop
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: i-manmeetdevgun-develop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: i-manmeetdevgun-develop
    spec:
      containers:
      - image: superuserz/i-manmeetdevgun-develop:v1
        imagePullPolicy: Always
        name: i-manmeetdevgun-develop
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: i-manmeetdevgun-develop
  name: i-manmeetdevgun-develop
  namespace: default
spec:
  ports:
  - nodePort: 32755
    port: 30158
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-manmeetdevgun-develop
  sessionAffinity: None
  type: LoadBalancer